# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
exclude: '^$'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
    - id: pyupgrade
      args: [--py39-plus]
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - pydocstyle
        - pycodestyle
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.941
  hooks:
    - id: mypy
      types: [python]
      files: ^intellifire4py/.+\.py$
      additional_dependencies: [types-requests, pydantic]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
    -   id: markdown-toc
        # optional custom config:
        args: [--indent, "    ", -i]
