name: Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.9]
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Python modules
        run: |
          pip install --constraint=.github/workflows/constraints.txt \
            pre-commit black flake8 reorder-python-imports

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always
