name: Release

on:
  push:
    branches:
      - main
      - master
      - refactor

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing
      contents: write  # Required for creating tags
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      # Install UV using the official action with caching enabled
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      # Set up Python using UV and .python-version file
      - name: Set up Python
        run: uv python install

      # Install project dependencies
      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: python -c "import re; print(re.search(r'version = \"([^\"]+)\"', open('pyproject.toml').read()).group(1))"
          create-tag: true
          tag-template: v{VERSION}
          tag-annotation-template: Released version {VERSION}

      - name: Bump version for developmental release
        if: ${{ ! steps.check-version.outputs.tag }}
        run: |
          uv run uv version --bump patch
          new_version=$(grep -m1 "version =" pyproject.toml | cut -d '"' -f 2)
          sed -i "s/version = \"$new_version\"/version = \"$new_version.dev.$(date +%s)\"/" pyproject.toml

      - name: Build package
        run: uv run python -m build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Publish package on TestPyPI
        if: ${{ ! steps.check-version.outputs.tag }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
