permissions:
  contents: read
name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      # Install UV using the official action with caching enabled
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # Set up Python using UV and .python-version file
      - name: Set up Python
        run: uv python install

      # Install project dependencies
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      # Run tests with coverage
      - name: Run tests
        run: uv run pytest --cov=intellifire4py --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
