permissions:
  contents: read
name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      # Set up Python using the version from pyproject.toml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "pip"

      # Install UV using the official action
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.10"  # Pin to a specific version for stability
      
      # Setup and run tests
      - name: Setup and run tests
        run: |
          # Create and activate virtual environment
          uv venv
          source .venv/bin/activate
          
          # Install dependencies
          uv pip install -e ".[dev]"
          
          # Run tests with coverage
          python -m pytest --cov=intellifire4py --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
