permissions:
  contents: read
name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install uv
      - name: Setup virtual environment
        run: uv venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"
      - name: Run tests and generate coverage
        run: |
          source .venv/bin/activate
          uv run pytest --cov --cov-report=xml
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          # token: ${{ secrets.CODECOV_TOKEN }}  # Uncomment if repo is private
